# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - joerob-python-webjob-win

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build SslCertTester/SslCertTester.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish SslCertTester/SslCertTester.csproj -c Release -o ./publish

      - name: List publish contents (debug)
        run: |
          Write-Host "Contents of publish directory:"
          Get-ChildItem -Path ./publish -Recurse -Depth 2 | Select-Object FullName
          Write-Host "`nChecking for wwwroot:"
          Test-Path ./publish/wwwroot
          Write-Host "`nChecking for Bootstrap:"
          Test-Path ./publish/wwwroot/lib/bootstrap

      - name: Prepare deployment package
        run: |
          # Create a deployment folder with the correct structure
          New-Item -ItemType Directory -Path ./deploy -Force
          
          Write-Host "Source publish structure:"
          Get-ChildItem -Path ./publish -Recurse -Depth 2
          
          # Copy all files and folders from publish to deploy
          Copy-Item -Path ./publish/* -Destination ./deploy -Recurse -Force
          
          # If wwwroot exists in deploy, flatten it
          if (Test-Path ./deploy/wwwroot) {
            Write-Host "`nFlattening wwwroot..."
            # Move wwwroot contents to deploy root
            Get-ChildItem -Path ./deploy/wwwroot -Force | ForEach-Object {
              $dest = Join-Path ./deploy $_.Name
              if (Test-Path $dest) {
                Write-Host "Merging $($_.Name)..."
                Copy-Item -Path $_.FullName -Destination $dest -Recurse -Force
              } else {
                Write-Host "Moving $($_.Name)..."
                Move-Item -Path $_.FullName -Destination ./deploy -Force
              }
            }
            # Remove empty wwwroot folder
            Remove-Item -Path ./deploy/wwwroot -Force
          }
          
          Write-Host "`nFinal deployment package structure:"
          Get-ChildItem -Path ./deploy -Recurse -Depth 2
          Write-Host "`nChecking for lib/bootstrap:"
          Test-Path ./deploy/lib/bootstrap

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./deploy

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./app
      
      - name: Debug downloaded artifact
        run: |
          Write-Host "Contents of downloaded artifact:"
          Get-ChildItem -Path ./app -Recurse -Depth 2 | Select-Object FullName
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E145812C68A64B838035400487816730 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D411A9A6945C426198822DC436386DBA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FFDC0AB3F2C24A67B5124B92ED33DFFC }}

      - name: Create deployment ZIP
        run: |
          Write-Host "Contents to be zipped:"
          Get-ChildItem -Path ./app -Recurse -Depth 2 | Select-Object FullName
          
          Write-Host "`nCreating deployment ZIP..."
          Compress-Archive -Path ./app/* -DestinationPath ./deploy.zip -Force
          
          Write-Host "`nZIP created. Size:"
          Get-Item ./deploy.zip | Select-Object Length
          
          Write-Host "`nExtracting ZIP to verify contents..."
          Expand-Archive -Path ./deploy.zip -DestinationPath ./verify-zip -Force
          Write-Host "Checking for lib folder in extracted ZIP:"
          Test-Path ./verify-zip/lib/bootstrap
          
      - name: Deploy to Azure Web App via ZIP
        run: |
          Write-Host "Finding resource group..."
          $rg = az webapp list --query "[?name=='joerob-python-webjob-win'].resourceGroup" -o tsv
          Write-Host "Resource group: $rg"
          
          Write-Host "Deploying ZIP to Azure using az webapp deploy..."
          az webapp deploy --resource-group $rg --name joerob-python-webjob-win --src-path ./deploy.zip --type zip --clean true --restart true
          Write-Host "Deployment completed"
      
      - name: Restart App Service
        run: |
          Write-Host "Finding resource group for app..."
          $rg = az webapp list --query "[?name=='joerob-python-webjob-win'].resourceGroup" -o tsv
          if ($rg) {
            Write-Host "Restarting App Service in resource group: $rg"
            az webapp restart --name joerob-python-webjob-win --resource-group $rg
            Write-Host "App Service restarted successfully"
          } else {
            Write-Host "Could not find resource group, skipping restart"
          }
      
      - name: Verify deployment
        run: |
          Write-Host "Deployment completed. Verify at:"
          Write-Host "  App: https://joerob-python-webjob-win.azurewebsites.net/Documentation"
          Write-Host "  Kudu: https://joerob-python-webjob-win.scm.azurewebsites.net/DebugConsole"
          